services:
  postgres:
    image: postgres:16
    container_name: pharmastock_postgres
    environment:
      POSTGRES_DB: pharmastock_db
      POSTGRES_USER: pharmastock_user
      POSTGRES_PASSWORD: pharmastock_pass
    ports:
      - "5432:5432"
    volumes:
      - pharmastock_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pharmastock_user -d pharmastock_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pharmastock_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pharmastock.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    profiles: ["tools"]

volumes:
  pharmastock_pgdata:
